[workspace]
exclude = []
members = ["denops-debugger-wasm", "denops-debugger-cli", "v8-inspector-api-types"]
default-members = ["denops-debugger-wasm", "v8-inspector-api-types"]

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"

[profile.bench]
lto = true
opt-level = 3